<a href="https://colab.research.google.com/github/Varunpandey001/trial1/blob/branch1/varun_pandey_shapeai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
!pip install pandas
!pip install numpy


In [41]:
import numpy as np
import pandas as pd

Here we have imported the 2 libraries for using fumctions and packages present inside them.

In [42]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

Importing the iris dataset which we are going to use to train and test our algo.


In [43]:
print("Keys os iris dataset\n{}".format(iris_dataset.keys()))

Keys os iris dataset
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Displaying the key values of iris_dataset which is just like a dictionary.

In [44]:
print(iris_dataset['DESCR'][:200])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive


To display DESCR(description)(a String) of iris_dataset

In [45]:
print("Target Names:{}".format(iris_dataset['target_names']))

Target Names:['setosa' 'versicolor' 'virginica']


To display target names of flower species.

In [46]:
print("Feature Names:{}".format(iris_dataset['feature_names']))

Feature Names:['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Display features of species

In [47]:
print("Type of data:{}".format(type(iris_dataset['data'])))

Type of data:<class 'numpy.ndarray'>


In [48]:
print("Shape of data:{}".format(iris_dataset['data'].shape))

Shape of data:(150, 4)


In [49]:
print("Display first 5 data points\n{}".format(iris_dataset['data'][:5]))

Display first 5 data points
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [50]:
print("Shape of target\n{}".format(iris_dataset['target'].shape))

Shape of target
(150,)


In [51]:
print("Target\n{}".format(iris_dataset['target']))

Target
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Displaying target via their codes assigned to them.

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

Splitting the data set into 75% and 25% for training and testing respectively and thereby storing it in variables


In [53]:
print("X_train shape:{}".format(X_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("y_train shape:{}".format(y_train.shape))
print("y_test shape:{}".format(y_test.shape))

X_train shape:(112, 4)
X_test shape:(38, 4)
y_train shape:(112,)
y_test shape:(38,)


In [54]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

Creating a algo who can test and predict by itself

In [55]:
knn.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Train the model on train data points

In [39]:
X_new=np.array([[2,4,3,2]])
print("X_new.shape:{}".format(X_new.shape))

X_new.shape:(1, 4)


In [57]:
prediction=knn.predict(X_new)
print("Prediction:{}".format(prediction))
print("Predicted target name:{}".format(iris_dataset['target_names'][prediction]))

Prediction:[1]
Predicted target name:['versicolor']


In [59]:
#Testing for the above data point

In [60]:
y_pred=knn.predict(X_test)
print("Test set predictions:\n{}".format(y_pred))

Test set predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [63]:
#Calculating percent accuracy
print("test score {}".format((np.mean(y_pred==y_test)*100)))

test score 97.36842105263158
